{% set name = "neptune-sklearn" %}
{% set package_name = "neptune_sklearn" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 744dae321d7443e23465053ca7946e031ab4e1830fd5f06e0241e4f5ba748cd3

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - neptune-client >=0.9
    - python >=3.6
    - scikit-learn >=0.24.1
    - scikit-plot >=0.3.7
    - yellowbrick >=1.3

test:
  imports:
    - neptune_sklearn
    - neptune_sklearn.impl
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Scikit-Learn
  doc_url: https://github.com/neptune-ai/neptune-sklearn/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-sklearn

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - shnela
    - twolodzko
    - AleksanderWWW
    - PatrykGala
    - Raalsky
