{% set name = "neptune-sklearn" %}
{% set package_name = "neptune_sklearn" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 2635224b27b0e3fdb8361ecd3a3c88eb68c471cad77212c39ab2feb072673682

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - neptune-client >=0.9
    - python >=3.6
    - scikit-learn >=0.24.1
    - scikit-plot >=0.3.7
    - yellowbrick >=1.3

test:
  imports:
    - neptune_sklearn
    - neptune_sklearn.impl

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Scikit-Learn
  doc_url: https://github.com/neptune-ai/neptune-sklearn/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-sklearn

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - shnela
    - Raalsky
    - twolodzko
    - AleksanderWWW
    - PatrykGala
